-- MySQL Script generated by MySQL Workbench
-- Thu Jun  8 12:08:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ataviada
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ATAVIADA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ATAVIADA` ;

-- -----------------------------------------------------
-- Schema ATAVIADA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ATAVIADA` DEFAULT CHARACTER SET utf8 ;
USE `ATAVIADA` ;

-- -----------------------------------------------------
-- Table `ATAVIADA`.`Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATAVIADA`.`Stock` ;

CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Stock` (
  `talla` VARCHAR(3) NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`talla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATAVIADA`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Proveedor` (
  `codigo_proveedor` INT NOT NULL,
  `nombre_proveedor` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATAVIADA`.`Producto` ;

CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Producto` (
  `codigo_producto` INT NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `Stock_talla` VARCHAR(3) NOT NULL,
  `Proveedor_codigo_proveedor` INT NOT NULL,
  PRIMARY KEY (`codigo_producto`),
  INDEX `fk_Producto_Stock1_idx` (`Stock_talla` ASC) VISIBLE,
  INDEX `fk_Producto_Proveedor1_idx` (`Proveedor_codigo_proveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Stock1`
    FOREIGN KEY (`Stock_talla`)
    REFERENCES `ATAVIADA`.`Stock` (`talla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Proveedor1`
    FOREIGN KEY (`Proveedor_codigo_proveedor`)
    REFERENCES `ATAVIADA`.`Proveedor` (`codigo_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATAVIADA`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Cliente` (
  `codigo_cliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATAVIADA`.`Pago` ;

CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Pago` (
  `codigo_transaccion` INT NOT NULL,
  `forma_pago` VARCHAR(45) NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `total` DECIMAL NOT NULL,
  PRIMARY KEY (`codigo_transaccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATAVIADA`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Pedido` (
  `fecha_pedido` DATE NOT NULL,
  `fecha_prevista` DATE NOT NULL,
  `fecha_entrega` DATE NULL,
  `Cliente_codigo_cliente` INT NOT NULL,
  `Pago_codigo_transaccion` INT NOT NULL,
  PRIMARY KEY (`fecha_pedido`, `fecha_prevista`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_codigo_cliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Pago1_idx` (`Pago_codigo_transaccion` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_codigo_cliente`)
    REFERENCES `ATAVIADA`.`Cliente` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Pago1`
    FOREIGN KEY (`Pago_codigo_transaccion`)
    REFERENCES `ATAVIADA`.`Pago` (`codigo_transaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATAVIADA`.`Reserva` ;

CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Reserva` (
  `numero_identificacion` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `Cliente_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`numero_identificacion`),
  INDEX `fk_Reserva_Cliente1_idx` (`Cliente_codigo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Cliente1`
    FOREIGN KEY (`Cliente_codigo_cliente`)
    REFERENCES `ATAVIADA`.`Cliente` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`Linea_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATAVIADA`.`Linea_Pedido` ;

CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Linea_Pedido` (
  `Producto_codigo_producto` INT NOT NULL,
  `Pedido_fecha_pedido` DATE NOT NULL,
  `Pedido_fecha_prevista` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unidad` DECIMAL NOT NULL,
  PRIMARY KEY (`Producto_codigo_producto`, `Pedido_fecha_pedido`, `Pedido_fecha_prevista`),
  INDEX `fk_Producto_has_Pedido_Pedido1_idx` (`Pedido_fecha_pedido` ASC, `Pedido_fecha_prevista` ASC) VISIBLE,
  INDEX `fk_Producto_has_Pedido_Producto1_idx` (`Producto_codigo_producto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Pedido_Producto1`
    FOREIGN KEY (`Producto_codigo_producto`)
    REFERENCES `ATAVIADA`.`Producto` (`codigo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_fecha_pedido` , `Pedido_fecha_prevista`)
    REFERENCES `ATAVIADA`.`Pedido` (`fecha_pedido` , `fecha_prevista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`Reserva_Del_Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ATAVIADA`.`Reserva_Del_Stock` ;

CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Reserva_Del_Stock` (
  `Reserva_numero_identificacion` INT NOT NULL,
  `Stock_talla` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Reserva_numero_identificacion`, `Stock_talla`),
  INDEX `fk_Reserva_has_Stock_Stock1_idx` (`Stock_talla` ASC) VISIBLE,
  INDEX `fk_Reserva_has_Stock_Reserva1_idx` (`Reserva_numero_identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_has_Stock_Reserva1`
    FOREIGN KEY (`Reserva_numero_identificacion`)
    REFERENCES `ATAVIADA`.`Reserva` (`numero_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_has_Stock_Stock1`
    FOREIGN KEY (`Stock_talla`)
    REFERENCES `ATAVIADA`.`Stock` (`talla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
