-- MySQL Script generated by MySQL Workbench
-- Wed Jan 18 17:11:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ATAVIADA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ATAVIADA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ATAVIADA` DEFAULT CHARACTER SET utf8 ;
USE `ATAVIADA` ;

-- -----------------------------------------------------
-- Table `ATAVIADA`.`MODO_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`MODO_PAGO` (
  `codigo_cuenta` INT NOT NULL,
  `fecha_pago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_cuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`PRODUCTO` (
  `cod_producto` INT NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `categoria_por_sexo` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `precio` DECIMAL NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `MODO_PAGO_codigo_cuenta` INT NOT NULL,
  PRIMARY KEY (`cod_producto`, `MODO_PAGO_codigo_cuenta`),
  INDEX `fk_PRODUCTO_MODO_PAGO1_idx` (`MODO_PAGO_codigo_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_MODO_PAGO1`
    FOREIGN KEY (`MODO_PAGO_codigo_cuenta`)
    REFERENCES `ATAVIADA`.`MODO_PAGO` (`codigo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`PROVEEDOR` (
  `codigo_proveedor` INT NOT NULL,
  `nombre_proveedor` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `PRODUCTO_cod_producto` INT NOT NULL,
  PRIMARY KEY (`codigo_proveedor`, `PRODUCTO_cod_producto`),
  INDEX `fk_PROVEEDOR_PRODUCTO1_idx` (`PRODUCTO_cod_producto` ASC) VISIBLE,
  CONSTRAINT `fk_PROVEEDOR_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_cod_producto`)
    REFERENCES `ATAVIADA`.`PRODUCTO` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`CLIENTE` (
  `codigo_cliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `teléfono` VARCHAR(9) NULL DEFAULT NULL,
  `DNI` VARCHAR(9) NOT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `CLIENTE_codigo_cliente_invitado` INT NOT NULL,
  `descuento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_cliente`),
  INDEX `fk_CLIENTE_CLIENTE1_idx` (`CLIENTE_codigo_cliente_invitado` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codigo_cliente_invitado`)
    REFERENCES `ATAVIADA`.`CLIENTE` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`RESERVA` (
  `numero_identificacion` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`numero_identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`TARJETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`TARJETA` (
  `digitos` INT NOT NULL,
  `fecha_caducidad` DATETIME NOT NULL,
  `MODO_PAGO_codigo_cliente` INT NOT NULL,
  INDEX `fk_TARJETA_MODO_PAGO_idx` (`MODO_PAGO_codigo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_TARJETA_MODO_PAGO`
    FOREIGN KEY (`MODO_PAGO_codigo_cliente`)
    REFERENCES `ATAVIADA`.`MODO_PAGO` (`codigo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`BIZUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`BIZUM` (
  `nombre_cuenta` VARCHAR(45) NOT NULL,
  `MODO_PAGO_codigo_cliente` INT NOT NULL,
  INDEX `fk_BIZUM_MODO_PAGO1_idx` (`MODO_PAGO_codigo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_BIZUM_MODO_PAGO1`
    FOREIGN KEY (`MODO_PAGO_codigo_cliente`)
    REFERENCES `ATAVIADA`.`MODO_PAGO` (`codigo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`ProductoApareceReserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`ProductoApareceReserva` (
  `PRODUCTO_cod_producto` INT NOT NULL,
  `RESERVA_numero_identificacion` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`PRODUCTO_cod_producto`, `RESERVA_numero_identificacion`),
  INDEX `fk_PRODUCTO_has_RESERVA_RESERVA1_idx` (`RESERVA_numero_identificacion` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_RESERVA_PRODUCTO1_idx` (`PRODUCTO_cod_producto` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_RESERVA_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_cod_producto`)
    REFERENCES `ATAVIADA`.`PRODUCTO` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_RESERVA_RESERVA1`
    FOREIGN KEY (`RESERVA_numero_identificacion`)
    REFERENCES `ATAVIADA`.`RESERVA` (`numero_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`Alquila`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Alquila` (
  `CLIENTE_codigo_cliente` INT NOT NULL,
  `PRODUCTO_cod_producto` INT NOT NULL,
  `fecha_alquiler` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  `precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CLIENTE_codigo_cliente`, `PRODUCTO_cod_producto`, `fecha_alquiler`),
  INDEX `fk_CLIENTE_has_PRODUCTO1_PRODUCTO1_idx` (`PRODUCTO_cod_producto` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_PRODUCTO1_CLIENTE1_idx` (`CLIENTE_codigo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO1_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codigo_cliente`)
    REFERENCES `ATAVIADA`.`CLIENTE` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO1_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_cod_producto`)
    REFERENCES `ATAVIADA`.`PRODUCTO` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`PEDIDO` (
  `fecha_pedido` DATETIME NOT NULL,
  `fecha_prevista` DATETIME NOT NULL,
  `fecha_entrega` DATETIME NULL DEFAULT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha_pedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`ClienteHaceReserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`ClienteHaceReserva` (
  `RESERVA_numero_identificacion` INT NOT NULL,
  `CLIENTE_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`RESERVA_numero_identificacion`, `CLIENTE_codigo_cliente`),
  INDEX `fk_RESERVA_has_CLIENTE_CLIENTE1_idx` (`CLIENTE_codigo_cliente` ASC) VISIBLE,
  INDEX `fk_RESERVA_has_CLIENTE_RESERVA1_idx` (`RESERVA_numero_identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVA_has_CLIENTE_RESERVA1`
    FOREIGN KEY (`RESERVA_numero_identificacion`)
    REFERENCES `ATAVIADA`.`RESERVA` (`numero_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_has_CLIENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codigo_cliente`)
    REFERENCES `ATAVIADA`.`CLIENTE` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`ClienteHacePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`ClienteHacePedido` (
  `PEDIDO_fecha_pedido` DATETIME NOT NULL,
  `CLIENTE_codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`PEDIDO_fecha_pedido`, `CLIENTE_codigo_cliente`),
  INDEX `fk_PEDIDO_has_CLIENTE_CLIENTE1_idx` (`CLIENTE_codigo_cliente` ASC) VISIBLE,
  INDEX `fk_PEDIDO_has_CLIENTE_PEDIDO1_idx` (`PEDIDO_fecha_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_has_CLIENTE_PEDIDO1`
    FOREIGN KEY (`PEDIDO_fecha_pedido`)
    REFERENCES `ATAVIADA`.`PEDIDO` (`fecha_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_has_CLIENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codigo_cliente`)
    REFERENCES `ATAVIADA`.`CLIENTE` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ATAVIADA`.`LineaPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`LineaPedido` (
  `PRODUCTO_cod_producto` INT NOT NULL,
  `PRODUCTO_MODO_PAGO_codigo_cuenta` INT NOT NULL,
  `PEDIDO_fecha_pedido` DATETIME NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`PRODUCTO_cod_producto`, `PRODUCTO_MODO_PAGO_codigo_cuenta`, `PEDIDO_fecha_pedido`),
  INDEX `fk_PRODUCTO_has_PEDIDO_PEDIDO1_idx` (`PEDIDO_fecha_pedido` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_PEDIDO_PRODUCTO1_idx` (`PRODUCTO_cod_producto` ASC, `PRODUCTO_MODO_PAGO_codigo_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_PEDIDO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_cod_producto` , `PRODUCTO_MODO_PAGO_codigo_cuenta`)
    REFERENCES `ATAVIADA`.`PRODUCTO` (`cod_producto` , `MODO_PAGO_codigo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_fecha_pedido`)
    REFERENCES `ATAVIADA`.`PEDIDO` (`fecha_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- 
-- 
-- 
CREATE TABLE IF NOT EXISTS `ATAVIADA`.`Stock` (
  `cantidad` INT NOT NULL,
  `talla` VARCHAR(1) NULL,
  `PRODUCTO_cod_producto` INT NOT NULL,
  `PRODUCTO_MODO_PAGO_codigo_cuenta` INT NOT NULL,
  PRIMARY KEY (`PRODUCTO_cod_producto`, `PRODUCTO_MODO_PAGO_codigo_cuenta`),
  CONSTRAINT `fk_Stock_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_cod_producto` , `PRODUCTO_MODO_PAGO_codigo_cuenta`)
    REFERENCES `ATAVIADA`.`PRODUCTO` (`cod_producto` , `MODO_PAGO_codigo_cuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
